### ISSUE TITLE
About dataloader NCMAPSS

### ISSUE THREAD

**Issue by marshellhu-hebut** [Frank-Wang-oss/GNN_RUL_Benchmarking#1]
Hello, author. I'm reproducing your code and trying to replicate the NCMAPSS dataset in your previous FCSTGNN project. May I ask why, when reading the Xv data in Data_Process/Data_read_NCMAPSS.py, the line df_Xv = pd.DataFrame(data=X_v[:, 0:2], columns=['T40', 'P30']) only takes the values of two sensors? Also, if I want to modify your dataloader into the previous project, is there anything I need to be aware of? I would greatly appreciate your response.

**Comment by Frank-Wang-oss** [comment]
For the first question, yes only two sensors from virtual sensors are extracted (because others have little influence on performance).
For the second question, I dont think there is anything else to be awared. I think you can directly use the processed NCMPS data into the FCSTGNN project. (But if there is any problem you can let me know).

Thanks for your interest to our works.
